<?php

namespace AppBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * TransferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransferRepository extends EntityRepository
{
    public function getActivePrices()
    {
        $qb = $this->createQueryBuilder('t')
            ->where('t.isActive = true')
            ;

        $prices = array();
        /** @var Transfer $transfer */
        foreach($qb->getQuery()->getResult() as $transfer)
        {
            $key = sprintf('%s|%s-%s|%s', $transfer->getDestination()->getId(), $transfer->getMinPax(), $transfer->getMaxPax(), $transfer->getRoundTrip());
            $prices[$key] = $transfer->getPrice();
        }

        return $prices;
    }
}
